apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qmail-server.fullname" . }}-pvc
  labels:
    {{- include "qmail-server.labels" . | nindent 4 }}
    component: mail-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mail.storage.size }}


