apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jaeger.fullname" . }}-pvc
  labels:
    {{ include "jaeger.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jaeger.storage.size }}
