apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{ include "jaeger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "jaeger.selectorLabels" . | nindent 4 }}
