apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  labels:
    {{ include "gitlab-runner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8093
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "gitlab-runner.selectorLabels" . | nindent 4 }}
