apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitlab-runner.fullname" . }}-pvc
  labels:
    {{ include "gitlab-runner.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitlab-runner.storage.size }}
