apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "roundcube-webmail.fullname" . }}-pvc
  labels:
    {{- include "roundcube-webmail.labels" . | nindent 4 }}
    component: webmail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.webmail.storage.size }}


