apiVersion: v1
kind: Service
metadata:
  name: {{ include "roundcube-webmail.fullname" . }}
  labels:
    {{- include "roundcube-webmail.labels" . | nindent 4 }}
    component: webmail
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "roundcube-webmail.selectorLabels" . | nindent 4 }}
    component: webmail


