apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb-database.fullname" . }}-pvc
  labels:
    {{- include "mongodb-database.labels" . | nindent 4 }}
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}

