apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-database.fullname" . }}
  labels:
    {{- include "mongodb-database.labels" . | nindent 4 }}
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongodb-database.selectorLabels" . | nindent 4 }}
    component: database

