apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{ include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "kafka.selectorLabels" . | nindent 4 }}
