apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.fullname" . }}-secret
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.argocd.admin.password | b64enc | quote }}
