apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "argocd.fullname" . }}-pvc
  labels:
    {{ include "argocd.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.argocd.storage.size }}
