apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd.fullname" . }}
  labels:
    {{ include "argocd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "argocd.selectorLabels" . | nindent 4 }}
