apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-secret
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
