apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jenkins.fullname" . }}-pvc
  labels:
    {{ include "jenkins.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.storage.size }}
