apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-database.fullname" . }}-secret
  labels:
    {{- include "postgres-database.labels" . | nindent 4 }}
type: Opaque
data:
  database-name: {{ .Values.database.credentials.databaseName | b64enc }}
  database-user: {{ .Values.database.credentials.username | b64enc }}
  database-password: {{ .Values.database.credentials.password | b64enc }}

