apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-database.fullname" . }}
  labels:
    {{- include "postgres-database.labels" . | nindent 4 }}
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-database.selectorLabels" . | nindent 4 }}
    component: database

