apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-database.fullname" . }}
  labels:
    {{- include "mssql-database.labels" . | nindent 4 }}
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "mssql-database.selectorLabels" . | nindent 4 }}
    component: database

