apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "efk-stack.fullname" . }}-elasticsearch-pvc
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
    component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.efk.elasticsearch.storage.size }}
