apiVersion: v1
kind: Service
metadata:
  name: {{ include "efk-stack.fullname" . }}-kibana
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
    component: kibana
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.efk.kibana.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "efk-stack.selectorLabels" . | nindent 4 }}
    component: kibana
