apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rabbitmq.fullname" . }}-pvc
  labels:
    {{ include "rabbitmq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage.size }}
