apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{ include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 15672
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "rabbitmq.selectorLabels" . | nindent 4 }}
