apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.rabbitmq.admin.password | b64enc | quote }}
