apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.fullname" . }}
  labels:
    {{ include "sonarqube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{ include "sonarqube.selectorLabels" . | nindent 4 }}
