apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-database.fullname" . }}
  labels:
    {{- include "mariadb-database.labels" . | nindent 4 }}
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    {{- include "mariadb-database.selectorLabels" . | nindent 4 }}
    component: database

