apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.keycloak.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
