apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.keycloak.admin.password | b64enc | quote }}
  db-password: {{ .Values.keycloak.database.password | b64enc | quote }}
